@startuml
class Kostum {
  +id: int
  +nama: String
  +harga: float
  +deskripsi: String
  +stok: int
  +getKeterangan(): String
}

class Pembeli {
  +id: int
  +nama: String
  +alamat: String
  +membeliKostum(): void
}

class Penjual {
  +id: int
  +nama: String
  +alamat: String
  +menjualKostum(): void
}

class Admin {
  +id: int
  +nama: String
  +mengelolaKostum(): void
}

Kostum "1" -- "0..*" Pembeli : membeli
Kostum "1" -- "0..*" Penjual : menjual
Kostum "1" -- "0..1" Admin : mengelola

@enduml